name: Publish NuGet.org

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Use .NET 7.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
        
      - name: Building
        run: dotnet build Notification.Wpf\Notification.Wpf.csproj -c Release
        
      - name: Packing
        run: |                    
          dotnet build Notification.Wpf/Notification.Wpf.csproj -c Release
          dotnet pack Notification.Wpf/Notification.Wpf.csproj -c Release

      - name: Publish GitHub
        run: |
          dotnet nuget push "**/*.nupkg" --skip-duplicate --source https://nuget.pkg.github.com/Platonenkov/index.json -k ${{secrets.GITHUB_TOKEN}}
          dotnet nuget push "**/*.snupkg" --skip-duplicate --source https://nuget.pkg.github.com/Platonenkov/index.json -k ${{secrets.GITHUB_TOKEN}}

      - name: Publish NuGet
        run: |
          dotnet nuget push "**/*.nupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGETAPIKEY }} 
          dotnet nuget push "**/*.snupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGETAPIKEY }}
